package com.hg.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageAllPropertiesEquals(Image expected, Image actual) {
        assertImageAutoGeneratedPropertiesEquals(expected, actual);
        assertImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageAllUpdatablePropertiesEquals(Image expected, Image actual) {
        assertImageUpdatableFieldsEquals(expected, actual);
        assertImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageAutoGeneratedPropertiesEquals(Image expected, Image actual) {
        assertThat(expected)
            .as("Verify Image auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageUpdatableFieldsEquals(Image expected, Image actual) {
        assertThat(expected)
            .as("Verify Image relevant properties")
            .satisfies(e -> assertThat(e.getPath()).as("check path").isEqualTo(actual.getPath()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getUpdatedDate()).as("check updatedDate").isEqualTo(actual.getUpdatedDate()))
            .satisfies(e -> assertThat(e.getImageFile()).as("check imageFile").isEqualTo(actual.getImageFile()))
            .satisfies(
                e -> assertThat(e.getImageFileContentType()).as("check imageFile contenty type").isEqualTo(actual.getImageFileContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageUpdatableRelationshipsEquals(Image expected, Image actual) {
        assertThat(expected)
            .as("Verify Image relationships")
            .satisfies(e -> assertThat(e.getProperty()).as("check property").isEqualTo(actual.getProperty()))
            .satisfies(e -> assertThat(e.getReview()).as("check review").isEqualTo(actual.getReview()));
    }
}
